import { Listing } from "./types";

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: "lst_1",
    title: "سفينة صيد مبردة حديثة - المرزوقي 22م",
    titleEn: "Modern Refrigerated Fishing Vessel - Al Marzouqi 22m",
    category: "ships",
    categoryEn: "Fishing Vessels",
    price: 28000000,
    year: 2018,
    condition: "used_excellent",
    conditionEn: "Excellent Used",
    specifications: "طول: 22 متر، عرض: 6 متر، عمق الغاطس: 2.5 متر، الهيكل: فولاذ بحري، سعة ثلاجة التجميد: 12 طن، الحمولة الإجمالية: 45 طن",
    specificationsEn: "Length: 22m, Beam: 6m, Draft: 2.5m, Hull: Marine Steel, Freezing Capacity: 12 Tons, Gross Tonnage: 45T",
    location: "ميناء بوهارون، تيبازة، الجزائر",
    locationEn: "Port of Bouharoun, Tipaza, Algeria",
    type: "sale",
    image: "https://images.unsplash.com/photo-1516641396056-0ce60a37defc?w=600&auto=format&fit=crop&q=80",
    ownerName: "الحاج لخضر البوهاروني",
    ownerPhone: "+213 551-402910",
    ownerId: "own_101",
    description: "سفينة صيد سردين بالجر مجهزة بمعدات تبريد يابانية حديثة، نظام ملاحة غارمن (Garmin) وباحث عن الأسماك ثلاثي الأبعاد. المحرك الأساسي كاتر بيلر (Caterpillar) بقوة 650 حصان بحالة ممتازة وخضع لصيانة شاملة مؤخراً بموانئ الجزائر.",
    descriptionEn: "Refrigerated sardine trawler equipped with state-of-the-art Japanese cooling systems, Garmin 3D fish finder, and reliable navigation. Main Caterpillar 650HP engine is in pristine condition post major overhaul in Algeria."
  },
  {
    id: "lst_2",
    title: "محرك ياماها خارجي 250 حصان بأربعة أشواط",
    titleEn: "Yamaha 250HP Four-Stroke Outboard Motor",
    category: "engines",
    categoryEn: "Marine Engines",
    price: 2200000,
    year: 2021,
    condition: "used_excellent",
    conditionEn: "Excellent Used",
    specifications: "قوة: 250 حصان، عمود طويل جداً (Ultra Long Shaft)، حقن وقود إلكتروني (EFI)، ساعات العمل: 240 ساعة فقط، موديل: FL250DET",
    specificationsEn: "Power: 250 HP, Ultra Long Shaft, EFI, Operating Hours: 240 hours only, Model: FL250DET",
    location: "ميناء وهران الجديد، الجزائر",
    locationEn: "New Port of Oran, Algeria",
    type: "sale",
    image: "https://images.unsplash.com/photo-1544923246-77307dd654cb?w=600&auto=format&fit=crop&q=80",
    ownerName: "العم صالح الوهراني",
    ownerPhone: "+213 661-897451",
    ownerId: "own_102",
    description: "محرك ياماها خارجي مستورد مباشر من الوكيل الرسمي بالجزائر، نظيف جداً وصيانته دورية بالدقة الكاملة. لم يتعرض لارتفاع حرارة أو حوادث بحرية. مثالي لقوارب النزهة وقوارب الصيد السريعة.",
    descriptionEn: "Genuine Yamaha outboard engine imported from authorized national dealer in Algeria. Super clean with strict routine oil/filter servicing. Perfectly runs for leisure cruisers and heavy-duty speed fishing multi-hulls."
  },
  {
    id: "lst_3",
    title: "يخت كروز سياحي عائلي فاخر - أزيموت 43 قدم للإيجار",
    titleEn: "Luxurious Azimut 43ft Cruiser Yacht for Charter",
    category: "ships",
    categoryEn: "Yachts & Cruisers",
    price: 120000,
    year: 2016,
    condition: "used_excellent",
    conditionEn: "Excellent Used",
    specifications: "طول: 43 قدم (13 متر)، الكبائن: 2 غرف نوم + صالون، محرك مزدوج فولفو بنتا 435 حصان ديزل، السعة المعتمدة: 12 فرد",
    specificationsEn: "Length: 43ft (13m), Cabins: 2 beds + salon, Twin Volvo Penta D6-435HP engines, Capacity: 12 persons max",
    location: "ميناء سيدي فرج، الجزائر العاصمة",
    locationEn: "Sidi Fredj Marina, Algiers, Algeria",
    type: "rent",
    image: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=600&auto=format&fit=crop&q=80",
    ownerName: "شركة صولبان للملاحة والترفيه البجائي",
    ownerPhone: "+213 770-345678",
    ownerId: "own_103",
    description: "يخت كلاسيكي مبهر متاح للإيجار اليومي أو الأسبوعي بسيدي فرج مع طاقم جزائري خبير وجاهز للخدمة. يشمل السعر أدوات الصيد الرياضي والشواء البحري والمشروبات الباردة لرحلات ممتعة بالساحل الجزائري.",
    descriptionEn: "Stunning cruiser yacht available for daily or weekly charter at Sidi Fredj Marina. Experienced Algerian crew and offshore catering included. Well equipped for sport fishing adventures in the Algerian coastal waters."
  },
  {
    id: "lst_4",
    title: "محرك ديزل داخلي فولفو بنتا D13 ثنائي التيربو",
    titleEn: "Volvo Penta D13 Twin-Turbo Inboard Marine Engine",
    category: "engines",
    categoryEn: "Marine Engines",
    price: 5400000,
    year: 2015,
    condition: "used_good",
    conditionEn: "Good Used",
    specifications: "القدرة: 800 حصان، 6 أسطوانات مستقيمة، نظام التوجيه الإلكتروني EVC-E، معدل ساعات التشغيل: 1600 ساعة",
    specificationsEn: "Power: 800 HP, In-line 6 Cylinders, EVC-E Electronic Vessel Control, Hours Run: 1,600 hrs",
    location: "ميناء بجاية البحري، الجزائر",
    locationEn: "Port of Bejaia, Algeria",
    type: "sale",
    image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&auto=format&fit=crop&q=80",
    ownerName: "المهندس أمين البجاوي",
    ownerPhone: "+213 556-781290",
    ownerId: "own_104",
    description: "محرك ديزل بحري احترافي عالي العزم للسفن واليخوت المتوسطة والكبيرة بميناء بجاية. نظيف ميكانيكياً ومفحوص تحت إشراف مهندسين بحريين جزائريين معتمدين. جاهز للتركيب المباشر.",
    descriptionEn: "Heavy-duty commercial inboard diesel motor. Outstanding torque output. Certified by Algerian marine surveyors at Bejaia port, perfect fit for industrial deep-sea boats, ready for installation."
  },
  {
    id: "lst_5",
    title: "جهاز رادار وسونار احترافي فورونو ثلاثي الحزمة",
    titleEn: "Furuno Multi-Beam Professional Sonar & Radar Array",
    category: "gear",
    categoryEn: "Navigational Gear",
    price: 950000,
    year: 2022,
    condition: "new",
    conditionEn: "Brand New",
    specifications: "رادار 4 كيلو واط، مدى مسح 48 ميل بحري، شاشة لمس ملونة 12 إنش مضادة للتوهج، سونار CHIRP لعمق 800 متر",
    specificationsEn: "Radar 4kW, Sweep Range 48NM, 12-inch anti-glare colored touch screen, CHIRP Sonar reaches 800m",
    location: "ميناء الغزوات، تلمسان، الجزائر",
    locationEn: "Port of Ghazaouet, Tlemcen, Algeria",
    type: "sale",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80",
    ownerName: "المعلم مراد الجيجلي",
    ownerPhone: "+213 662-349081",
    ownerId: "own_105",
    description: "جهاز سونار ورادار بحري جديد بكرتونه لم يفتح أبداً مع كامل ملحقات الأسلاك وهوائي قبة الدوران العلوية جاهز للتسليم في الغزوات أو وهران. يدعم الخرائط البحرية للساحل الجزائري والبحر الأبيض المتوسط.",
    descriptionEn: "Brand new high-grade Furuno multi-beam sonar & marine radar assembly inside original packing. Includes active marine navigation maps of the Algerian basin and Mediterranean Sea. Available in Ghazaouet or Oran."
  },
  {
    id: "lst_6",
    title: "شباك صيد غزل عملاقة لصيد التونة والسردين",
    titleEn: "Heavy-Duty Seine Netting for Tuna & Sardine",
    category: "gear",
    categoryEn: "Fishing Gear",
    price: 550000,
    year: 2023,
    condition: "new",
    conditionEn: "Brand New",
    specifications: "الطول: 600 متر، الارتفاع: 80 متر، مادة غزل نايلون مضاعف الشد، دعامات توازن رصاصية، العوامات: عالية الكثافة الإيطالية",
    specificationsEn: "Length: 600m, Depth: 80m, Dual-tensile braided nylon mesh, Lead weights, Italian high-buoyancy floats",
    location: "ميناء عنابة، الجزائر",
    locationEn: "Port of Annaba, Algeria",
    type: "sale",
    image: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=600&auto=format&fit=crop&q=80",
    ownerName: "الكابتن ياسين العنّابي",
    ownerPhone: "+213 771-883322",
    ownerId: "own_106",
    description: "شباك صيد تجارية ثقيلة مقاومة لملوحة البحر العالية والتآكل الشمسي. مصممة لسفن الصيد المتوسطة لمواجهة التيارات المائية القوية بالشرق الجزائري. خيوط معززة تمنع هروب الأسماك الكبيرة.",
    descriptionEn: "Industrial seine marine net built targeting large schooling fishes (tuna, sardines, mackerels) customized for East Algerian tides and waters. Reinforced double knot design prevents damage during heavy sea hauling."
  }
];
