import { Listing } from "./types";

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: "lst_1",
    title: "سفينة صيد مبردة حديثة - المرزوقي 22م",
    titleEn: "Modern Refrigerated Fishing Vessel - Al Marzouqi 22m",
    category: "ships",
    categoryEn: "Fishing Vessels",
    price: 185000,
    year: 2018,
    condition: "used_excellent",
    conditionEn: "Excellent Used",
    specifications: "طول: 22 متر، عرض: 6 متر، عمق الغاطس: 2.5 متر، الهيكل: فولاذ بحري، سعة ثلاجة التجميد: 12 طن، الحمولة الإجمالية: 45 طن",
    specificationsEn: "Length: 22m, Beam: 6m, Draft: 2.5m, Hull: Marine Steel, Freezing Capacity: 12 Tons, Gross Tonnage: 45T",
    location: "ميناء طنجة، المغرب",
    locationEn: "Port of Tangier, Morocco",
    type: "sale",
    image: "https://images.unsplash.com/photo-1516641396056-0ce60a37defc?w=600&auto=format&fit=crop&q=80",
    ownerName: "الحاج عبد القادر البقالي",
    ownerPhone: "+212 661-234567",
    ownerId: "own_101",
    description: "سفينة صيد سردين بالجر مجهزة بمعدات تبريد يابانية حديثة، نظام ملاحة غارمن (Garmin) وباحث عن الأسماك ثلاثي الأبعاد. المحرك الأساسي كاتر بيلر (Caterpillar) بقوة 650 حصان بحالة ممتازة وخضع لصيانة شاملة مؤخراً.",
    descriptionEn: "Refrigerated sardine trawler equipped with state-of-the-art Japanese cooling systems, Garmin 3D fish finder, and reliable navigation. Main Caterpillar 650HP engine is in pristine condition post major overhaul."
  },
  {
    id: "lst_2",
    title: "محرك ياماها خارجي 250 وعاء بأربعة أشواط",
    titleEn: "Yamaha 250HP Four-Stroke Outboard Motor",
    category: "engines",
    categoryEn: "Marine Engines",
    price: 14200,
    year: 2021,
    condition: "used_excellent",
    conditionEn: "Excellent Used",
    specifications: "قوة: 250 حصان، عمود طويل جداً (Ultra Long Shaft)، حقن وقود إلكتروني (EFI)، ساعات العمل: 240 ساعة فقط، موديل: FL250DET",
    specificationsEn: "Power: 250 HP, Ultra Long Shaft, EFI, Operating Hours: 240 hours only, Model: FL250DET",
    location: "ميناء دبي البحري، الإمارات",
    locationEn: "Dubai Harbour, UAE",
    type: "sale",
    image: "https://images.unsplash.com/photo-1544923246-77307dd654cb?w=600&auto=format&fit=crop&q=80",
    ownerName: "الكابتن راشد الفلاسي",
    ownerPhone: "+971 50-1234567",
    ownerId: "own_102",
    description: "محرك ياماها خارجي مستورد مباشر من الوكيل الرسمي، نظيف جداً وصيانته دورية بالجرام الزيتي. لم يتعرض لارتفاع حرارة أو حوادث بحرية. مثالي لقوارب النزهة وقوارب الصيد السريعة.",
    descriptionEn: "Genuine Yamaha outboard engine imported from authorized national dealer. Super clean with strict routine oil/filter servicing. Perfectly runs for leisure cruisers and heavy-duty speed fishing multi-hulls."
  },
  {
    id: "lst_3",
    title: "يخت سياحي عائلي فاخر - أزيموت 43 قدم للإيجار",
    titleEn: "Luxurious Azimut 43ft Cruiser Yacht for Charter",
    category: "ships",
    categoryEn: "Yachts & Cruisers",
    price: 850,
    year: 2016,
    condition: "used_excellent",
    conditionEn: "Excellent Used",
    specifications: "طول: 43 قدم (13 متر)، الكبائن: 2 غرف نوم + صالون، محرك مزدوج فولفو بنتا 435 حصان ديزل، السعة المعتمدة: 12 فرد",
    specificationsEn: "Length: 43ft (13m), Cabins: 2 beds + salon, Twin Volvo Penta D6-435HP engines, Capacity: 12 persons max",
    location: "ميناء مارينا، الإسكندرية، مصر",
    locationEn: "Marina Port, Alexandria, Egypt",
    type: "rent",
    image: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=600&auto=format&fit=crop&q=80",
    ownerName: "مجموعة سيسكيب للملاحة",
    ownerPhone: "+20 100-7654321",
    ownerId: "own_103",
    description: "يخت كلاسيكي مبهر متاح للإيجار اليومي أو الأسبوعي مع طاقم خبير ومضيفة طعام. يشمل السعر أدوات الصيد الرياضي، الطعم الطازج، والمشروبات الباردة. رحلات صيد أو نزهات عائلية فاخرة.",
    descriptionEn: "Stunning cruiser yacht available for daily or weekly charter. Crew and offshore catering included in the price. Well equipped for sport fishing adventures, fresh baits, and pristine family sailing experiences."
  },
  {
    id: "lst_4",
    title: "محرك ديزل داخلي فولفو بنتا D13 ثنائي التيربو",
    titleEn: "Volvo Penta D13 Twin-Turbo Inboard Marine Engine",
    category: "engines",
    categoryEn: "Marine Engines",
    price: 32000,
    year: 2015,
    condition: "used_good",
    conditionEn: "Good Used",
    specifications: "القدرة: 800 حصان، 6 أسطوانات مستقيمة، نظام التوجيه الإلكتروني EVC-E، معدل ساعات التشغيل: 1600 ساعة",
    specificationsEn: "Power: 800 HP, In-line 6 Cylinders, EVC-E Electronic Vessel Control, Hours Run: 1,600 hrs",
    location: "ميناء الشويخ، الكويت",
    locationEn: "Shuwaikh Port, Kuwait",
    type: "sale",
    image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&auto=format&fit=crop&q=80",
    ownerName: "شركة وارف للمعدات البحرية",
    ownerPhone: "+965 9988-7766",
    ownerId: "own_104",
    description: "محرك ديزل بحري احترافي عالي العزم للسفن واليخوت المتوسطة والكبيرة. نظيف ميكانيكياً ومفحوص تحت إشراف معتمد. جاهز للشحن والاستبدال المباشر مع ناقل حركة زاحف معتمد.",
    descriptionEn: "Heavy-duty commercial inboard diesel motor. Outstanding torque output. Certified by marine surveyors, perfect fit for industrial deep-sea boats, ready for swift global or regional shipping."
  },
  {
    id: "lst_5",
    title: "جهاز رادار وسونار احترافي فورونو ثلاثي الحزمة",
    titleEn: "Furuno Multi-Beam Professional Sonar & Radar Array",
    category: "gear",
    categoryEn: "Navigational Gear",
    price: 5900,
    year: 2022,
    condition: "new",
    conditionEn: "Brand New",
    specifications: "رادار 4 كيلو واط، مدى مسح 48 ميل بحري، شاشة لمس ملونة 12 إنش مضادة للتوهج، سونار CHIRP لعمق 800 متر",
    specificationsEn: "Radar 4kW, Sweep Range 48NM, 12-inch anti-glare colored touch screen, CHIRP Sonar reaches 800m",
    location: "ميناء جدة الإسلامي، السعودية",
    locationEn: "Jeddah Islamic Port, KSA",
    type: "sale",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80",
    ownerName: "المهندس أسامة الحازمي",
    ownerPhone: "+966 54-8889900",
    ownerId: "own_105",
    description: "جهاز سونار ورادار بحري جديد بكرتونه لم يفتح أبداً مع كامل ملحقات الأسلاك وهوائي قبة الدوران العلوية. يدعم الخرائط البحرية للخليج العربي والبحر الأحمر بالكامل مع كفالة دولية لعامين.",
    descriptionEn: "Brand new high-grade Furuno multi-beam sonar & marine radar assembly inside original packing. Includes active marine navigational maps of Red Sea and Arabian Gulf. 2-Year global warranty."
  },
  {
    id: "lst_6",
    title: "شباك صيد غزل عملاقة لصيد التونة والسردين",
    titleEn: "Heavy-Duty Seine Netting for Tuna & Sardine",
    category: "gear",
    categoryEn: "Fishing Gear",
    price: 3400,
    year: 2023,
    condition: "new",
    conditionEn: "Brand New",
    specifications: "الطول: 600 متر، الارتفاع: 80 متر، مادة غزل نايلون مضاعف الشد، دعامات توازن رصاصية، العوامات: عالية الكثافة الإيطالية",
    specificationsEn: "Length: 600m, Depth: 80m, Dual-tensile braided nylon mesh, Lead weights, Italian high-buoyancy floats",
    location: "ميناء جرجيس، تونس",
    locationEn: "Port of Zarzis, Tunisia",
    type: "sale",
    image: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=600&auto=format&fit=crop&q=80",
    ownerName: "المعلم سفيان الجراية",
    ownerPhone: "+216 22-555666",
    ownerId: "own_106",
    description: "شباك صيد تجارية ثقيلة مقاومة لملوحة البحر العالية والتآكل الشمسي. مصممة لسفن الصيد المتوسطة لمواجهة التيارات المائية القوية. خيوط معززة تمنع هروب الأسماك الكبيرة.",
    descriptionEn: "Industrial seine marine net built targeting large schooling fishes (tuna, sardines, mackerels). Reinforced double knot design prevents damage during heavy sea hauling."
  }
];
